# site config
title: Jeux et défis informatiques de Sherbrooke (JDIS)
email: info@jdis.ca
description: >- # this means to ignore newlines until the next key
  Jeux et défis informatiques de Sherbrooke (JDIS) est un groupe d'étudiants
  en informatique de l'Université de Sherbrooke.
url: "https://jdis.ca/"

# social (to be moved into a _data file)
facebook_page_link: "https://www.facebook.com/JDISherbrooke"
facebook_members_link: "https://www.facebook.com/groups/jdisherbrooke"
github_link: "https://github.com/JDIS"
slack_link: "https://jdis.slack.com"
youtube_link: "https://www.youtube.com/channel/UCtvgOm5GYpuuEL6pXoEoylg"

# pages config
permalink: /:title/
include: ["_pages"] 

# assets config
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# plugins
markdown: kramdown
plugins:
  - jekyll-feed

# excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
